export const LYRICS_CONTAINER = '[style^=--lyrics]'
export const TRANSLATED_LYRIC = 'translated-lyric'
export const ORIGINAL_LYRIC = 'original-lyric'
export const ROMANIZED_LYRIC = 'romanized-lyric'
export const LYRIC_SELECTOR = '[data-testid="fullscreen-lyric"]'
export const FULLSCREEN_BUTTON = '[data-testid="fullscreen-mode-button"]'
export const FULLSCREEN_LYRIC = '.npv-lyrics__text-wrapper>p'
export const SONG_TITLE = '[data-testid="now-playing-widget"]'
