export const LYRICS_CONTAINER = '[style^=--lyrics]'
export const TRANSLATED_LYRIC = 'translated-lyric'
export const ORIGINAL_LYRIC = 'original-lyric'
export const ROMANIZED_LYRIC = 'romanized-lyric'
export const LYRIC_SELECTOR = '[data-testid="lyrics-line"]'
export const FULLSCREEN_CONTAINER = '[style^=--cinema]'
export const SONG_TITLE = '[data-testid="now-playing-widget"]'
